### ISSUE TITLE
If-Statements

### ISSUE THREAD

**Issue by SpencerPark** [SpencerPark/MellowD#3]
## TODO
- [x]  Decide on syntax
- [x]  Implement a boolean expression parser  #1
- [x]  Fill in the truth table #2 

#### ~~Traditional procedural if-statements.~~
```java
if (condition) {
    code
} else if (other) {
    code
} else {
    code
}
```
#### ~~Guarded statements.~~
```
{ code } when (condition)
or { code } when (condition)
or { code }
```
#### ~~More verbose guarded statements.~~
```
only do { <code> } when <condition>
or { <code> } when <condition>
or { <code> }
```

### Syntax
```
do { <code> } if <condition>
else do { <code> } if <condition>
else do { <code> }
```
